language: node_js

notifications:
  email:
  - surgesoft@gmail.com

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=coverage

after_script:
  - cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js