sudo: false

language: node_js

node_js:
  - 10

cache:
  directories:
    - $HOME/.npm

notifications:
  email:
  - surgesoft@gmail.com

script:
- npm install codecov -g
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=coverage

after_success:
  - codecov